og1600_60_arm_ip:        10.23.80.60
terminal_server_ip:     192.168.43.200
og1600_60_arm_port:      2061
og1600_60_atom_port:     2062
og1600_60_arm_login:        arristi
og1600_60_atom_login:        arristi

bootfile_ssid_ath2:          c_60_24_3
bootfile_ssid_ath3:          c_60_24_4
bootfile_ssid_ath4:          c_60_24_5
bootfile_ssid_ath5:          c_60_24_6
bootfile_ssid_ath6:          c_60_24_7
bootfile_ssid_ath10:          c_60_05_3
bootfile_ssid_ath11:          c_60_05_4
bootfile_ssid_ath12:          c_60_05_5
bootfile_ssid_ath13:          c_60_05_6
bootfile_ssid_ath14:          c_60_05_7

bootfile_acs24:         1 6 11
bootfile_acs05:         149 161

bootfile_beacon_int_ath2:         "150"
bootfile_beacon_int_ath3:         "150"
bootfile_beacon_int_ath4:         "150"
bootfile_beacon_int_ath5:         "150"
bootfile_beacon_int_ath6:         "150"
bootfile_beacon_int_ath10:         "150"
bootfile_beacon_int_ath11:         "150"
bootfile_beacon_int_ath12:         "150"
bootfile_beacon_int_ath13:         "150"
bootfile_beacon_int_ath14:         "150"
